services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/app

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - '4200:80'
    depends_on:
      - backend

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
